version: '3.1'

# networks:
#   bb:

services:

  mongo:
    image: mongo:5.0.24-focal
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - ./mongo:/data/db
    # networks:
    #   - bb
    ports:
      - "27017:27017"
