import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import AppScripts from './app-scripts'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: {
    template: '%s | Create Next App',
    default: 'Create Next App',
  },
  description: 'Generated by create next app',
  metadataBase: new URL('http://localhost'),
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      {/* <body className={`${inter.className} antialiased`}> */}
      <body className='antialiased bg-gray-50 dark:bg-slate-900'>
        {children}
        <AppScripts /> 
      </body>
    </html>
  )
}
